version: '3'
services:
  servicer-contracts:
    build:
      context: .
      args:
        OS_UID: "${OS_UID}"
        OS_GID: "${OS_GID}"
    container_name: servicer-contracts
    entrypoint: tail -f /dev/null
    volumes:
    - .:/module
